language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

env:
  matrix:
  - REACT=16.7

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - rm -f package-lock.json && yarn install
  - yarn add jest@latest
  - yarn run build
  - yarn run test -- -u --coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
