export const FETCH_SINGLE_PRODUCT_PENDING = "FETCH_SINGLE_PRODUCT_PENDING";
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
export const FETCH_SINGLE_PRODUCT_ERROR = "FETCH_SINGLE_PRODUCT_ERROR";